### ISSUE TITLE
Blank status screen

### ISSUE THREAD

**Issue by harmlessdrudge** [dave-p/TVHadmin#10]
First, many thanks for this really very nice add-on to TVHeadend. It works beautifully and the Timeline display is much nicer to use than any alternative I have.

I use LibreElec as my HTPC box but could see no way of installing it there (the /var directory contents made no sense to me). It must be possible to package it as an add-on via .kodi/addons but I wouldn't know where to begin. On a Raspberry Pi (w Raspbian Stretch), however, it was trivial. Just needed to 

`sudo chown -R www-data:www-data /var/www/html/TVHadmin/data`

The only thing not to work was the Status link. It yields a blank screen. 

Checking the web server error log (/var/log/lighttpd/eror.log) yields

`2020-08-12 13:54:23: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/TVHadmin/status.php:84
2020-08-12 13:54:23: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2020-08-12 13:54:23: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/TVHadmin/TVHadmin.php(5): include_once()
2020-08-12 13:54:23: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2020-08-12 13:54:23: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/TVHadmin/status.php on line 84
2020-08-12 13:54:28: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/TVHadmin/status.php:84
2020-08-12 13:54:28: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2020-08-12 13:54:28: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/TVHadmin/TVHadmin.php(5): include_once()
2020-08-12 13:54:28: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2020-08-12 13:54:28: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/TVHadmin/status.php on line 84
`
I searched for "simplexml_load_file" and "undefined function" and discovered that it appears that PHP7.2 or later is required (am on 7.0). Will try to fix. Meanwhile, you may want to update the requirements.

Suggestion: in the event of only a single media tag being selected it should be an automatically selected default and not need checking on the Timeline screen (I use one called Default).

**Comment by dave-p** [comment]
Thanks for the compliments!

The issue with SimpleXML seems to be distribution-specific. The SimpleXML extension works with PHP 5 and later, and should be enabled by default. However Debian and RedHat (and maybe others) package it separately as php-xml. I use Arch so wasn't aware of the issue; I'll update the README.

Re the media tags, I'm really not happy with the way they work at the moment. I'll bear your comment in mind.

**Comment by harmlessdrudge** [comment]
Sorry, I overlooked the option to pre-check a Tag for some screens.

My Media Tags list disappears off the side of the screen on a 1920x1200 display. A drop-down list might work better. I only use 3 bouquets of my own but quite a few are created automatically. An option to filter those _might_ be handy (anything not beginning with "***"?) or just list starred ones first perhaps.

Timeline length: I'm using a default of 4 hours and typically look at it sometime between 6pm and 9pm. For me having the retrieval default to 6 hours with a pushbutton choice of how many hours to display on the Timeline display would be nice, if that's easily doable. It not I can live with adjusting the configuration occasionally (mainly to check on things I might want to record in the early hours).

I love the search feature!

Next suggestion: make it possible to created a list of alert terms and then a "Highlight" button to list all entries with matching text.

**Comment by dave-p** [comment]
I like the idea of a drop-down list for media tags, it would work much better on a phone screen. I'll have a tinker...
