### ISSUE TITLE
What's on Tonight?

### ISSUE THREAD

**Issue by harmlessdrudge** [dave-p/TVHadmin#11]
Suggestion: add a 2nd what's on button with a start time chooseable in preferences for What's on Tonight?

**Comment by dave-p** [comment]
Hmmm... Or make the Timeline screen scrollable?

**Comment by harmlessdrudge** [comment]
That would work, sure. Almost all of my TV viewing is in the evening from 9pm and the question is usually "is there anything worth watching on tonight" and the answer is usually no. The next question, fwiw, is often "What day is X on" (an episode of something; don't always remember). The next is "What channel is X on?"

I've only recently been able to integrate selected free to air terrestrial and satellite channels into a single EPG in Kodi. While it works it's much less attractive and less accessible and doesn't permit quick interrogation.

**Comment by dave-p** [comment]
I've created a new branch called "timeline-scroll" which includes the scrollable timeline screen. There is one known bug; using the scroll arrows resets any changes to the Media Tag selections.

**Comment by dave-p** [comment]
I believe this is now fully working and I've pushed the change into Master.

**Comment by harmlessdrudge** [comment]
Great! Thanks, and sorry I didn't get back to you sooner. Will try it.

**Comment by harmlessdrudge** [comment]
Looks good. Scroll worked ok. Assume you must have fixed the bug you mentioned?

**Comment by dave-p** [comment]
Yes, scrolling preserves any changes to Media Tag selections. Thanks for testing.
