### ISSUE TITLE
Filter channels to be displayed in Timeline, what's on now

### ISSUE THREAD

**Issue by skycamel** [dave-p/TVHadmin#15]
I just started to use your program as I was looking for something where I could see conflicting recordings. Thanks!
However, I've a request. Would it be possible to select what channels are viewable in the Timeline and What's on Now?
Maybe based on Favourites? In other words, make a Timeline and What's on Now view for the Favourites.
That would be very helpful also to program my recordings as in the Favourites I can decide in what order they show up so I can putt those channels that I usually record from together. Like this, I can directly see if there's a conflict and not after I programmed them and check in Timers.

**Comment by dave-p** [comment]
Could you use TVHeadend channel tags to do this? Create a new tag called "timeline favourites" and add it to your favourite channels, then use the filter in TVHadmin to only include those channels in the Timeline screen.

**Comment by skycamel** [comment]
Great idea, just did a quick test and it's working "as advertised" :-)
I didn't realize that those tags actually were coming from TVHeadend (and not your program)
Thanks for your great software, very useful.
