### ISSUE TITLE
Installation instructions for LibreElec missing

### ISSUE THREAD

**Issue by arcasys** [dave-p/TVHadmin#19]
TVHAdmin-JS looks very promising and is exactly what I'm looking for after moving from VDR to Tvheadend (I've used vdradmin-am for a long time). Unfortunately the installation instructions do not cover LibreElec.
LibreElec has directorles  
~/.kodi/addons/service.tvheadend42 and
~/.kodi/userdata/addon_data/service.tvheadend42
I've tested with unpacking master.zip into both directories to no avail.
I was not able to find a web root path for tvheadend. Although  http://myserver:9981/extjs.html works, a file _extjs.html_ cannot be found on the system

**Comment by dave-p** [comment]
I've never used LibreElec but as I understand it the operating system and applications are stored in a read-only filesystem, so adding TVHadmin-JS will likely be difficult.

One possibility if you have a web server on your network would be to use the PHP version of TVHadmin.

**Comment by arcasys** [comment]
Thanks for your prompt answer. In LibreElec, only /flash (which is /boot in other Pi systems like raspbian) is mounted read only.
Going to another server is not an option because I'd have to move Tvheadend as well and the Kodi integration would be gone, if I understand things right.
This is why I did more research:  
I cannot find any trace of a web server with port 9981 nor any file extjs.html on the system. 
Going to http://myserver:9981 takes me to a box asking for my Tvheadend credentials and then opens the Tvheadend web interface. The browser line now always shows  `http://myserver:9981/extjs.html`. So far the web interface is working fine.
The command `find / -name extjs.html` yields no result. 
My guess is that  Tvheadend has a built in web server listening to port 9981 and a file `extjs.html` simply does not really exist. This makes it impossible to tell the web root.
Poking around a bit more I came up with the following which confirms my assumption

```
myserver:~/.kodi # grep -r extjs ./addons/service.tvheadend42/
./addons/service.tvheadend42/bin/tvheadend:extjs.html
./addons/service.tvheadend42/bin/tvheadend:src/webui/static/extjs/resources/css/xtheme-%s.css
```
...and so on. Here we have our path src/webui/static/ built into the `tvheadend` binary.

This raises the following questions:

- Why could  TVAdmin-JS not make it into the LibreElec Addon Repository? I found one thread dated 2020 asking how to install TVAdmin-JS in LibreElec and there was no proper answer. 
- Is there so few interest in the community for a clean and usable web interface for Tvheadend?  Tvheadends own web interface is lacking all the nice features like timeline etc and appears fairly basic, to put  it polite
- Would it be an option for you to approach the LibreElec community with a request to integrate your addon into the official LibreElec repository? This would probably be a value add for the community.

**Comment by arcasys** [comment]
I just realized this issue belongs to TVHadmin-JS and I inadvertently opened it in the wrong project. I close it here, create a new issue in TVHadmin-JS, and point to to this issue for the beginning of the story...
Sorry for the inconvenience
