### ISSUE TITLE
mixed results

### ISSUE THREAD

**Issue by seancmalloy777** [dave-p/TVHadmin#3]
latest master tvhadmin
tvheadend 4.2.8-4~g9f7ab681a 
apache 2.4.25 - via mod proxy / FPM FastCGI 
php7.0 w/ JSON ext 
no open_basedir set in php.ini, cannot set globally
cannot set per vhost via fpm (ProxyFCGISetEnvIf ) until apache 2.4.26

so. tvhadmin can connect to tvheadend and see/select channels and view epg on "Channels" page
but What's On Now? and Timeline are blank
my channels are tagged "TV" so changed $types = [1=>"TV"]; did not fix
verified access to /api/epg/grid etc

any ideas?

**Comment by dave-p** [comment]
Is the "Recordings" page also blank? If so then the problem may be in the mapping of service types to channel tags. There is also a known problem if two or more services of different types are mapped to the same channel (HD and SD for example).

The "no open_basedir set in php.ini, cannot set globally" may be preventing you from saving preferences.

I won't be able to look into this in detail for a week or so.

**Comment by seancmalloy777** [comment]
yes, recordings is also blank. services are only mapped to 1 tag TV. i verified that channels are being mapped to correct tag. if you could explain the following, maybe i can figure this out

$types = [1=>"SDTV",2=>"Radio",17=>"HDTV",22=>"SDTV",23=>"SDTV",24=>"SDTV",25=>"HDTV",
	 26=>"HDTV",27=>"HDTV",28=>"HDTV",29=>"HDTV",30=>"HDTV",31=>"UHDTV"];

get back at me when you can, thanks

**Comment by dave-p** [comment]
The service type does not use TVH tags, the type numbers are supplied by the mux. See https://github.com/dave-p/TVH-API-docs/wiki/mpegts#mpegtsservicegrid

What is the value of "dvb_servicetype" for your services when calling api/mpegts/service/grid?

Are there any PHP errors in your Apache error log?

**Comment by seancmalloy777** [comment]
"dvb_servicetype":0 

is this why it is not creating correct type-based tags when mapped?
services are being tagged "SDTV" and "TV channels" but have wrong type

apache log - PHP Notice:  Undefined offset: 0 
i am assuming this error is due to the service type error

is there a fix? or do i have to install another tvheadend deb pkg or compile myself?

**Comment by seancmalloy777** [comment]
just added 0=>"HDTV" to $types in include.php. it looks like it is working now. i do not know if this was to right way to fix it (or if there is something wrong with tvheadend service mapping). thanks for pointing me in the right direction

**Comment by dave-p** [comment]
As a matter of interest, what TV are you receiving? Are you using IPTV?

**Comment by seancmalloy777** [comment]
i probably should have lead with that, i have a Hauppauge HVR-955Q Hybrid TV (ATSC/NTSC/QAM) tuner, but i am only using ATSC-T (us-ATSC-center-frequencies-8VSB)

**Comment by seancmalloy777** [comment]
so after installing multiple versions of deb pkgs and compiling tvheadend myself i always get the same results, scans categorize all channels as dvb_servicetype:0, i guess it is what it is, but i do have a few more questions, i am trying to bring more functionality into the timeline page, among other things, i made the channel name a link to its stream and also trying to make  button to submit its value '{$c['uuid']}'  to a form with <video>, is that possible? i know that the embedded video works if i set the src manually. also, is it possible to sort channels by channelNumber in timeline, instead of alphabetically ?

**Comment by dave-p** [comment]
I've created a new branch of the project called 'mediatags'. This branch uses the TVHeadend channel tags to filter channels and recordings instead of the media type, which should work with your ATSC system. One possible problem is if there are a lot of channel tags or the descriptions are very long, then the interface might become untidy, especially on a small screen such as a phone. Also I suppose there ought to be a config option to select which tags to use.

I'll add your suggestion about channel numbers to my 'todo' list. LCNs are not very useful here; we have the same services on both terrestrial and satellite TV but they use different channel numbers - and the terrestrial ones are continually changing.

I'm not sure I understand what you are trying to do with a button, sorry.

**Comment by seancmalloy777** [comment]
button? understandable, i didn't want go into great detail and you cant paste in code. breakdown goal:
I want to use button to pass the value='{$c['uuid']}' in timeline (across forms, button is in timeline, video is in head) into embedded < video > with onclick='blablablaSubmit()'. it looks like it is possible. make any sense? basically make play buttons for embedded video. you would understand if/when you see my ui, I tweaked the layout/css like the new hopper ui (video preview window in top right corner, navi on top, etc)

regardless, your project is awesome, a perfect web interface for tvheadend. you take paypal donations? it seems like you put some time into this, let me buy you a beer

**Comment by dave-p** [comment]
Your appreciation is sufficient reward.
I'll push the tag changes into master when I've tested them some more. Closing.
