### ISSUE TITLE
Channels to be ordered by channel number instead of alphabetically

### ISSUE THREAD

**Issue by sundalon** [dave-p/TVHadmin#4]
Hi dave-p,
I just stumbled over this because I was looking for an enhancement to TVHeadends EPG view.
Coming from VDR I'm somewhat used to vdradmin-am and the likes, so thank you for making the transition easier for me. ;-)

Now my question: is it possible to make the sorting of channels configurable? I prefer sorting by channel numbers over alphabetically.

TIA,
sun

**Comment by dave-p** [comment]
Configuring the sort order of channels would be straightforward. But I'm sure you would like to see the LCNs against the channel names, so the changes would go rather deeper.

I'll do some experiments.

**Comment by dave-p** [comment]
I've added a new branch called "LCNsort", which has a config item to change the channel sort order, and added the LCN to the "What's on now", "Timeline" and "Channels" screens. I'm not sure the LCN adds much value to the other screens.

**Comment by sundalon** [comment]
Thanks, working as desired. Currently my "What's On Now", "Timeline" and "Recordings" are coming up empty. Anything I can do here? My TVH version is 4.3-1793~gbc769bfa9

These are my current settings. All "Show in ..." items have no options.
![Selection_003](https://user-images.githubusercontent.com/18375196/59666975-3a516900-91b6-11e9-9afd-298a7f6cd412.png)

**Comment by dave-p** [comment]
OK. The "Media Tags to use for selection" item determines which media choices appear at the top of the "What's On Now", "Timeline" and "Recordings" screens. You haven't ticked any so you have no choices on those screens so nothing is displayed. Once you have ticked some media choices and clicked 'Save' then the "Show in..." lines will offer these same media choices as defaults for the screens - you can then make temporary changes on the screens themselves.

I see this is not at all obvious on a first-time installation. Perhaps if the Media Tags were all pre-ticked on first start-up, then you could switch off the ones you don't need.

**Comment by sundalon** [comment]
Thank you for this clarification. I'm now able to add channels. Unfortunately this is not working for Media Tags which include spaces like "Alle Sender" or "Dritte Programme".

**Comment by dave-p** [comment]
Hopefully fixed in latest commit to LCNsort branch (who know that PHP replaces spaces in POST variable names with underscores??).

I've also pre-ticked the "All" filter settings in the Configuration screen, so a first-time user will see everything.

**Comment by sundalon** [comment]
Yep, works now. Thanks for fixing!

**Comment by dave-p** [comment]
No problem. Thank you for finding a couple of bugs!
