### ISSUE TITLE
TVHadmin not working 

### ISSUE THREAD

**Issue by mohammadavr** [dave-p/TVHadmin#6]
Hi
I'v installed tvh 4.2.9 and set admin user name and password on ubuntu 16.04.
tvh work fine but tvhadmin not connect to it .
tvhadmin is on http-root and both on same server
on config page i set username and password and ip:port server and after save noting happened 
how can i debug ?

**Comment by dave-p** [comment]
TVH must be set to use either "Plain" or "Plain and Digest" authentication (Configuration->General->Base->HTTP Server Settings). Digest-only authentication doesn't work. Yes, OK, security, but you can configure your TVH users so they can only connect from your local network.

I need to update the installation instructions to include this point, also to investigate Digest auth.

**Comment by mohammadavr** [comment]
Ok solved 
thanks for help
