### ISSUE TITLE
Icon and tumb

### ISSUE THREAD

**Issue by luis52627** [dave-p/TVHadmin#7]
Hi Dave, can you consider put on What's on. the Icon of the channel, instead of channel name, and a thumb of the program..

I mean, the use of this:
"channelIcon":"imagecache/15799",
and
"image":"http://url/xxx.jpg"
Thanks

**Comment by dave-p** [comment]
I've never used icons with TVHeadend. Where do they come from, and what size are they?

**Comment by luis52627** [comment]
Example:
`<img class="x-epg-chicon" src="imagecache/6208">`
.x-epg-chicon {
    float: right;
    margin: 5px;
    width: 20%;
    max-height: 99px;
}
`<img class="x-epg-image" src="http://xxx.jpg">`
.x-epg-image {
    float: right;
    margin-left: 5px;
    margin-right: 5px;
    margin-bottom: 5px;
    width: 20%;
}

**Comment by dave-p** [comment]
Do you have some real URLs so I can download images to test?

**Comment by luis52627** [comment]
Sorry..
x-epg-chicon:
https://github.com/gigablue-support-org/templates_PiconsUpdater/tree/master/picon_all
x-epg-image:
![558553_resized_352x198](https://user-images.githubusercontent.com/55835054/76344153-01839200-62f9-11ea-99c7-a5e1c69bf203.jpg)

http://images.amcnetworks.com/amctv.pt/wp-content/uploads/2019/12/FEATURe_Wisting.jpg

**Comment by luis52627** [comment]
![1_0_1_76E_45_36_FFFF0000_0_0_0](https://user-images.githubusercontent.com/55835054/76344232-26780500-62f9-11ea-86ba-143c6054e01c.png)

**Comment by dave-p** [comment]
OK thanks. I've done some experiments with picons and they seem to work from my local network. However there is a problem with using TVHadmin over the internet where the TVH server is not accessible from the internet; the web server running TVHadmin must proxy the images. I'll try to find a way forward.

**Comment by dave-p** [comment]
That was easier than expected. There is a new GitHub branch "icons" which will show the channel icons in place of the channel name, and a config screen item to switch it on.

The icon size is manually set to 80 x 48 which works well on my desktop and mobile (Android). Hope it works for you.

**Comment by luis52627** [comment]
Ok try it but no image..
Code is:
http://myphpserver/tvhadmin/icon.php?image=imagecache/6261
and image is on:
http://iptvheadendserver:9981/imagecache/6261

Other thing what is "icon_public_url", we have to set any url?

**Comment by dave-p** [comment]
"icon_public_url" is what is shown under "Icon URL" under Configuration->Channel/EPG->Channels in the TVH GUI. It should be "imagecache/nnnn".

If you enter your image URL "http://iptvheadendserver:9981/imagecache/6261" into your web browser do you see the image?

Are there any errors in the webserver error log?

**Comment by luis52627** [comment]
Yes I see image..
ON Configuration->Channel/EPG->Channels I have:
http://myphpserver/picons/rtp.png
ON General I have:
http://myphpserver/picons/%C.png

Just a idea imagecache is the caching on Tvheadend (copy of the picon)...
On json you have imagecache/6208, but the file is:

http://iptvheadendserver:9981/imagecache/6208

Difference for thumb's icon images, that use the url from web...
Thanks for your time...

**Comment by dave-p** [comment]
These are my configuration settings:
![picons](https://user-images.githubusercontent.com/3237636/76679525-36cdff80-65d9-11ea-8e7f-d121aed2b424.png)
The "imagecache" files are just text files containing the URL of the icon, eg
```
{
        "url": "file:///home/hts/.hts/tvheadend/picons/1_0_1_C7A6_817_2_11A0000_0_0_0.png",
        "accessed": 1584178296,
        "updated": 1584178296
}
```

**Comment by dave-p** [comment]
If you're still not seeing the icons I've just pushed an update which may fix your problem.

**Comment by DominiqueRT** [comment]
It works for me. 
Can be usefull to have icons also for Timeline, Channels, Favourite Channels, ..
Thanks

**Comment by luis52627** [comment]
Sorry, but last days.... rrrrrrrrrrrrr... I have it and is working ok...
Can you add thumbs on screen=now..

**Comment by dave-p** [comment]
I've added channel icons to the Recordings screen.
I'm not sure about programme thumbnails. They would use up a lot of screen space, and TVHadmin is barely usable on mobile as it is. But you are welcome to experiment...
