### ISSUE TITLE
Bad Cursor position on Timeline

### ISSUE THREAD

**Issue by DominiqueRT** [dave-p/TVHadmin#9]
Cursor is not a the right position for some windows browsers : 
Chrome (80.0.3987.149 64bits)
![image](https://user-images.githubusercontent.com/7418677/77851000-a4cc1680-71d6-11ea-9e1c-ed4e3702a775.png)

Edge
![image](https://user-images.githubusercontent.com/7418677/77851013-b1e90580-71d6-11ea-9b7a-624510042045.png)

but **OK with Firefox** (74.0 (64 bits)): 
![image](https://user-images.githubusercontent.com/7418677/77851028-c5946c00-71d6-11ea-9f4a-d78476f3f72e.png)

**Comment by dave-p** [comment]
Hmmm it *did* work...

I've pushed a fix. Tested on Waterfox Classic, Firefox and Chromium for Linux, and Chromium for Android.

**Comment by DominiqueRT** [comment]
Thanks,

It works now
